site_name: Dutch Rose Media Libraries Documentation

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: light mode
      primary: amber
      accent: orange

    - scheme: default
      toggle:
        icon: material/weather-night
        name: dark mode
      primary: amber
      accent: orange

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
